### Transpose

In [1]:
import tensorflow as tf

In [6]:
a = tf.random.uniform(shape=(5,10, 4))

In [5]:
a.shape

TensorShape([5, 10])

In [10]:
b = tf.transpose(a, perm=[1,0, 2])

In [14]:
b.shape

TensorShape([10, 5, 4])

### Slicing

Tensorflow supports slicing just like `Numpy`

In [16]:
a = tf.constant([1,2,3,4,5,6])

In [18]:
tf.slice(a, begin=[1], size=[3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [33]:
b = tf.constant([[1,2,3,4,5,6], [2,3,4,5,6, 7], [3,4,5,6, 7, 8]])

In [35]:
tf.slice(a, begin=[0, 1], size=[2,5])

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]], dtype=int32)>

For multidimensional array, `begin` is the coordinate of the starting point and each ineteger in `size` refers to number of elements in each axis

You can also slice in python like ways

In [37]:
b[:2, 1:3]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 4]], dtype=int32)>

#### tf.gather

tf.gather can be used to access specific indices

In [43]:
tf.gather(b, indices=[0, 2])

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[1, 2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7, 8]], dtype=int32)>

In [44]:
tf.gather(b, indices=[[0, 2]])

<tf.Tensor: shape=(1, 2, 6), dtype=int32, numpy=
array([[[1, 2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7, 8]]], dtype=int32)>

In [45]:
t4 = tf.constant([[0, 5],
                  [1, 6],
                  [2, 7],
                  [3, 8],
                  [4, 9]])

In [46]:
tf.gather(t4, indices=[0,2,3])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[0, 5],
       [2, 7],
       [3, 8]], dtype=int32)>

### nest.flatten