##### Reference:
    https://www.tensorflow.org/guide/tensor

In [1]:
import tensorflow as tf

In [7]:
import numpy as np

In [8]:
tf.__version__

'2.3.0'

#### Tensor from Python List and numpy array

In [9]:
a = tf.constant([[3,4], [6,7]])

In [10]:
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [6, 7]], dtype=int32)>

In [11]:
b = tf.constant(np.array([[3,4], [6,7]]))

In [12]:
b

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[3, 4],
       [6, 7]])>

#### Numpy operations accepts `tensors`
#### Tensorflow operations accepts arrays

In [13]:
np.add([3,4], [6,7])

array([ 9, 11])

In [14]:
np.add(a,b)

array([[ 6,  8],
       [12, 14]])

In [15]:
tf.add([3,4], [6,7])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 9, 11], dtype=int32)>

In [16]:
tf.add(np.array([3,4]), np.array([6,7]))

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([ 9, 11])>

#### Getting Numpy values

In [17]:
b

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[3, 4],
       [6, 7]])>

In [18]:
b.numpy()

array([[3, 4],
       [6, 7]])

### Indexing in tensors

In [25]:
b[0]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([3, 4])>

##### Same Slicing rules apply as `numpy`

In [27]:
b[:,1]

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 7])>

#### Tensor Resizing or Reshaping

In [26]:
b.shape

TensorShape([2, 2])

#### While Reshaping, you have to make sure that the total number of element isn't altered

In [36]:
tf.reshape(b, [4, 1])

<tf.Tensor: shape=(4, 1), dtype=int64, numpy=
array([[3],
       [4],
       [6],
       [7]])>

In [31]:
x = tf.constant([[1], [2], [3]])
x.shape

TensorShape([3, 1])

In [33]:
tf.reshape(x, shape=[1,3])

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [47]:
y = tf.random.uniform([3,4])
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.9977968 , 0.9075507 , 0.30279195, 0.23636448],
       [0.24843657, 0.52669275, 0.2739346 , 0.72012734],
       [0.9478023 , 0.93668306, 0.06797659, 0.23521972]], dtype=float32)>

In [48]:
tf.reshape(y, [6,2])

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[0.9977968 , 0.9075507 ],
       [0.30279195, 0.23636448],
       [0.24843657, 0.52669275],
       [0.2739346 , 0.72012734],
       [0.9478023 , 0.93668306],
       [0.06797659, 0.23521972]], dtype=float32)>

##### Note: The tensors are `row-major` in memory. The elments of the reshaped tensors are picked up from the `row-major` version of the original matrix. This is evident from the above example

##### Also Note: Reshaping never swaps axes as the `row-major` elements are conserved in the reshaped tensor