**What is tf.Data and why do we need it?**

tf.data is tensorflow's own implementation of various data pipeline. You can use this API to Load and preprocess your data whthout writing custom codes in python or other libraries in python which makes the whole pipeline more faster making training process more efficient


In [11]:
import tensorflow as tf

### Extract

In [17]:
file_pattern = "/home/bxm200000/test_file.txt"

In [18]:
files = tf.data.Dataset.list_files(file_pattern)

In [19]:
dataset = tf.data.TFRecordDataset(files)

### Transform

In [20]:
dataset = dataset.shuffle(10000)

In [21]:
dataset = dataset.repeat(10)

In [ ]:
dataset = dataset.map(lambda x: transform_function(x))

In [ ]:
dataset = dataset.batch(BATCH_SIZE)

### Loading

In [23]:
for batch in dataset:
    pass

`tf.data` offers multiple utilities to make the input pipeline more efficient. One of the most important are `tf.data.Dataset`

In [10]:
tf.data.Dataset.reduce

<function tensorflow.python.data.ops.dataset_ops.DatasetV2.reduce(self, initial_state, reduce_func)>

`tf.data` CONVERTS USER DEFINED DATA TO GRAPHS IRRESPECTIVE OF RUNNING MODE

In [2]:
dataset1 = tf.data.Dataset.from_tensor_slices(tf.random.uniform([4, 10]))


In [3]:
dataset1

<TensorSliceDataset shapes: (10,), types: tf.float32>

In [9]:
tf.data.Dataset.from_tensor_slices([[1,2,3],[1,2,3]])

<TensorSliceDataset shapes: (3,), types: tf.int32>

In [32]:
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [26]:
dataset = tf.data.Dataset.from_tensors([8, 3, 0, 8, 2, 1])
dataset

<TensorDataset shapes: (6,), types: tf.int32>

In [33]:
dataset = dataset.map(lambda x:x)

In [34]:
dataset = dataset.batch(2)

In [35]:
for batch in dataset:
    print(batch)

tf.Tensor([8 3], shape=(2,), dtype=int32)
tf.Tensor([0 8], shape=(2,), dtype=int32)
tf.Tensor([2 1], shape=(2,), dtype=int32)
